name: Must run on custom runner

on: push

jobs:
  init:
      runs-on: self-hosted
      steps: 
        - run: echo "Hello there MATE"
        - run: echo $HOSTNAME
        - run: echo "git good scrub"
      
