name: Must run on custom runner

on: push

jobs:
  init:
      runs-on: self-hosted
      steps: 
        - run: echo "Hello there from down under"
        - run: echo $HOSTNAME
        - run: echo $SHELL
        - run: echo $PWD
      
